# Importing and Setting up the API

In [1]:
# Note: this was necessary even though I installed spotipy via my cmd because the shell and this kernel use different versions
# of python. So in order to install spotipy here, we need to install it using sys.executable and not regular python3.
import sys
!{sys.executable} -m pip install spotipy

Requirement already satisfied: spotipy in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (2.20.0)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from spotipy) (1.26.9)
Requirement already satisfied: six>=1.15.0 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from spotipy) (1.16.0)
Requirement already satisfied: requests>=2.25.0 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from spotipy) (2.27.1)
Requirement already satisfied: redis>=3.5.3 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from spotipy) (4.3.4)
Requirement already satisfied: deprecated>=1.2.3 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from redis>=3.5.3->spotipy) (1.2.13)
Requirement already satisfied: async-timeout>=4.0.2 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from redis>=3.5.3->spotipy) (4.0.2)
Requirement already satisfied: packaging>=20.4 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from redis>=3.5.3->spotipy) (21.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.25.0->spotipy) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.25.0->spotipy) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.25.0->spotipy) (2021.10.8)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from deprecated>=1.2.3->redis>=3.5.3->spotipy) (1.14.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\neela\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from packaging>=20.4->redis>=3.5.3->spotipy) (3.0.7)

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: C:\Users\neela\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import cred

For our web app, we're going to use the **Client Credentials** flow. This project is relatively small in scale, so this flow allows us to access a user's data without the need to implement refresh tokens.

In [4]:
# Authenticating (without user credentials)
cid = cred.client_ID
secret = cred.client_SECRET

client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager, requests_timeout=10)

In [4]:
# Random Test
weeknduri = 'spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ' # you don't need the 'spotify:artist:'
results = sp.artist_top_tracks(weeknduri) # dictionary
for i, track in enumerate(results['tracks'][:10]):
    print(f'{i+1}. ' + track['name'])

In [6]:
playlist_link = "https://open.spotify.com/playlist/37i9dQZEVXbNG2KDcFcKOF?si=1333723a6eff4b7f"
playlist_URI = playlist_link.split('/')[-1].split('?')[0] # extracts the URI from the link
playlist_URI

track_uris = []
for track in sp.playlist_tracks(playlist_URI)['items']:
    track_uris.append(track['track']['uri'])

# track_uris

['spotify:track:3nqQXoyQOWXiESFLlDF1hG',
 'spotify:track:0V3wPSX9ygBnCm8psDIegu',
 'spotify:track:4Dvkj6JhhA12EX05fT7y2e',
 'spotify:track:5ww2BF9slyYgNOk37BlC4u',
 'spotify:track:0bYg9bo50gSsH3LtXe2SQn',
 'spotify:track:4uUG5RXrOk84mYEfFvj3cK',
 'spotify:track:1bDbXMyjaUIooNwFE9wn0N',
 'spotify:track:2tTmW7RDtMQtBk7m2rYeSw',
 'spotify:track:2FRnf9qhLbvw8fu4IBXx78',
 'spotify:track:0QHEIqNKsMoOY5urbzN48u',
 'spotify:track:5IgjP7X4th6nMNDh4akUHb',
 'spotify:track:2EjXfH91m7f8HiJN1yQg97',
 'spotify:track:6Sq7ltF9Qa7SNFBsV5Cogx',
 'spotify:track:1RDvyOk4WtPCtoqciJwVn8',
 'spotify:track:7jtQIBanIiJOMS6RyCx6jZ',
 'spotify:track:73vIOb4Q7YN6HeJTbscRx5',
 'spotify:track:4h9wh7iOZ0GGn8QVp4RAOB',
 'spotify:track:1zsPaEkglFvxjAhrM8yhpr',
 'spotify:track:1IHWl5LamUGEuP4ozKQSXZ',
 'spotify:track:7vQbuQcyTflfCIOu3Uzzya',
 'spotify:track:0lLdorYw7lVrJydTINhWdI',
 'spotify:track:4k6Uh1HXdhtusDW5y8Gbvy',
 'spotify:track:53tfEupEzQRtVFOeZvk7xq',
 'spotify:track:561jH07mF1jHuk7KlaeF0s',
 'spotify:track:2LBqCSwhJGcFQeTHMVGwy3',
 'spotify:track:0WtM2NBVQNNJLh6scP13H8',
 'spotify:track:5Eax0qFko2dh7Rl2lYs3bx',
 'spotify:track:5XeFesFbtLpXzIVDNQP22n',
 'spotify:track:1xK59OXxi2TAAAbmZK0kBL',
 'spotify:track:0lizgQ7Qw35od7CYaoMBZb',
 'spotify:track:3k3NWokhRRkEPhCzPmV8TW',
 'spotify:track:5odlY52u43F5BjByhxg7wg',
 'spotify:track:2QjOHCTQ1Jl3zawyYOpxh6',
 'spotify:track:1xzi1Jcr7mEi9K2RfzLOqS',
 'spotify:track:6zJejIfVYLgjud3lTk4DLB',
 'spotify:track:3rWDp9tBPQR9z6U5YyRSK4',
 'spotify:track:6G12ZafqofSq7YtrMqUm76',
 'spotify:track:4ewazQLXFTDC8XvCbhvtXs',
 'spotify:track:5jQI2r1RdgtuT8S3iG8zFC',
 'spotify:track:6VhuP99TE6gYNQRJIlAWFD',
 'spotify:track:02MWAaffLxlfxAUY7c5dvx',
 'spotify:track:1IcR6RlgvDczfvoWJSSY2A',
 'spotify:track:2CeKVsFFXG4QzA415QygGb',
 'spotify:track:5PjdY0CKGZdEuoNab3yDmX',
 'spotify:track:2uFaJJtFpPDc5Pa95XzTvg',
 'spotify:track:54ipXppHLA8U4yqpOFTUhr',
 'spotify:track:6sCvvleqKbeyOkQDieBYgp',
 'spotify:track:31i56LZnwE6uSu3exoHjtB',
 'spotify:track:78Sw5GDo6AlGwTwanjXbGh',
 'spotify:track:4FyesJzVpA39hbYvcseO2d']

In [7]:
sp.audio_features(track_uris[0]) # this is method we can use to get features of songs

[{'danceability': 0.714,
  'energy': 0.472,
  'key': 2,
  'loudness': -7.375,
  'mode': 1,
  'speechiness': 0.0864,
  'acousticness': 0.013,
  'instrumentalness': 4.51e-06,
  'liveness': 0.266,
  'valence': 0.238,
  'tempo': 131.121,
  'type': 'audio_features',
  'id': '3nqQXoyQOWXiESFLlDF1hG',
  'uri': 'spotify:track:3nqQXoyQOWXiESFLlDF1hG',
  'track_href': 'https://api.spotify.com/v1/tracks/3nqQXoyQOWXiESFLlDF1hG',
  'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3nqQXoyQOWXiESFLlDF1hG',
  'duration_ms': 156943,
  'time_signature': 4}]

# Getting the data

In [8]:
import pandas as pd
import json

In [9]:
data_path = 'mpd.slice.0-999.json'
json_dict = json.loads(open(data_path).read()) # json.loads() deserializes a string representing json object and returns a python dictionary
# note: json.load(open(data_path)) would've done the same thing, loads works on strings and load works on file objects

playlists = json_dict['playlists'] # list of 
df = pd.json_normalize(playlists, record_path='tracks', meta='name') # record_path looks at 'tracks' in every playlist, meta grabs the playlist name

# df.to_csv('raw_data.csv')
df

# pd.read_json('mpd.slice.0-999.json').head()

,pos,artist_name,track_uri,artist_uri,track_name,album_uri,duration_ms,album_name,name
0,0,Missy Elliott,spotify:track:0UaMYEvWZi0ZqiDOoHU3YI,spotify:artist:2wIVse2owClT7go1WT98tk,Lose Control (feat. Ciara & Fat Man Scoop),spotify:album:6vV5UrXcfyQD1wu4Qo2I9K,226863,The Cookbook,Throwbacks
1,1,Britney Spears,spotify:track:6I9VzXrHxO9rA9A5euc8Ak,spotify:artist:26dSoYclwsYLMAKD3tpOr4,Toxic,spotify:album:0z7pVBGOD7HCIB7S8eLkLI,198800,In The Zone,Throwbacks
2,2,Beyoncé,spotify:track:0WqIKmW4BTrj3eJFmnCKMv,spotify:artist:6vWDO969PvNqNYHIOW5v0m,Crazy In Love,spotify:album:25hVFAxTlDvXbx2X2QkUkE,235933,Dangerously In Love (Alben für die Ewigkeit),Throwbacks
3,3,Justin Timberlake,spotify:track:1AWQoqb9bSvzTjaLralEkT,spotify:artist:31TPClRtHm23RisEBtV3X7,Rock Your Body,spotify:album:6QPkyl04rXwTGlGlcYaRoW,267266,Justified,Throwbacks
4,4,Shaggy,spotify:track:1lzr43nnXAijIGYnCT8M8H,spotify:artist:5EvFsr3kj42KNv97ZEnqij,It Wasn't Me,spotify:album:6NmFmPX56pcLBOFMhIiKvF,227600,Hot Shot,Throwbacks
...,...,...,...,...,...,...,...,...,...
67498,39,James Arthur,spotify:track:5uCax9HTNlzGybIStD3vDh,spotify:artist:4IWBUUAFIplrNtaOHcJPRM,Say You Won't Let Go,spotify:album:7oiJYvEJHsmYtrgviAVIBD,211466,Back from the Edge,thinking of you
67499,40,Big Words,spotify:track:0P1oO2gREMYUCoOkzYAyFu,spotify:artist:0sHN89qak07mnug3LVVjzP,The Answer,spotify:album:5jrsRHRAmetu5e7RRBoxj7,263679,"Hollywood, a Beautiful Coincidence",thinking of you
67500,41,Allan Rayman,spotify:track:2oM4BuruDnEvk59IvIXCwn,spotify:artist:6Yv6OBXD6ZQakEljaGaDAk,25.22,spotify:album:3CbNgBzI7r9o0F6VjH9sTY,189213,Roadhouse 01,thinking of you
67501,42,Jon Jason,spotify:track:4Ri5TTUgjM96tbQZd5Ua7V,spotify:artist:77bNdkKYBBmc30CisCA6tE,Good Feeling,spotify:album:2dZ7oVNQBeLlpoUYfbEsJP,194720,Good Feeling,thinking of you
67502,43,Grizfolk,spotify:track:5RVuBrXVLptAEbGJdSDzL5,spotify:artist:6Xa4nbrSTfbioA4lLShbjh,Cosmic Angel - Acoustic From Capitol Studios,spotify:album:7D6Y19tjm4DQNch39FeWpO,257194,Cosmic Angel,thinking of you

In [16]:
quick = pd.DataFrame(columns=["lengths"])
for i in range(len(playlists)):
    quick.loc[len(quick.index)] = len(playlists[i]['tracks'])

quick.iloc[:,0].mean(axis=0)

67.503

In [10]:
# Test
fd = pd.json_normalize(playlists, record_path='tracks')
fd.head()

,pos,artist_name,track_uri,artist_uri,track_name,album_uri,duration_ms,album_name
0,0,Missy Elliott,spotify:track:0UaMYEvWZi0ZqiDOoHU3YI,spotify:artist:2wIVse2owClT7go1WT98tk,Lose Control (feat. Ciara & Fat Man Scoop),spotify:album:6vV5UrXcfyQD1wu4Qo2I9K,226863,The Cookbook
1,1,Britney Spears,spotify:track:6I9VzXrHxO9rA9A5euc8Ak,spotify:artist:26dSoYclwsYLMAKD3tpOr4,Toxic,spotify:album:0z7pVBGOD7HCIB7S8eLkLI,198800,In The Zone
2,2,Beyoncé,spotify:track:0WqIKmW4BTrj3eJFmnCKMv,spotify:artist:6vWDO969PvNqNYHIOW5v0m,Crazy In Love,spotify:album:25hVFAxTlDvXbx2X2QkUkE,235933,Dangerously In Love (Alben für die Ewigkeit)
3,3,Justin Timberlake,spotify:track:1AWQoqb9bSvzTjaLralEkT,spotify:artist:31TPClRtHm23RisEBtV3X7,Rock Your Body,spotify:album:6QPkyl04rXwTGlGlcYaRoW,267266,Justified
4,4,Shaggy,spotify:track:1lzr43nnXAijIGYnCT8M8H,spotify:artist:5EvFsr3kj42KNv97ZEnqij,It Wasn't Me,spotify:album:6NmFmPX56pcLBOFMhIiKvF,227600,Hot Shot

# Extracting the features from the data

In [17]:
data_path = 'raw_data.csv'
df2 = pd.read_csv(data_path)
# df2['track_uri'] = df2['track_uri'].apply(lambda x: re.findall(r'\w+$', x)[0]) Not necessary lmao
# df2 = df2[:100]
df2
# for numrow in range(len(df)):
#     df['track_uri'][i]
# print(df2.shape)

,Unnamed: 0,pos,artist_name,track_uri,artist_uri,track_name,album_uri,duration_ms,album_name,name
0,0,0,Missy Elliott,spotify:track:0UaMYEvWZi0ZqiDOoHU3YI,spotify:artist:2wIVse2owClT7go1WT98tk,Lose Control (feat. Ciara & Fat Man Scoop),spotify:album:6vV5UrXcfyQD1wu4Qo2I9K,226863,The Cookbook,Throwbacks
1,1,1,Britney Spears,spotify:track:6I9VzXrHxO9rA9A5euc8Ak,spotify:artist:26dSoYclwsYLMAKD3tpOr4,Toxic,spotify:album:0z7pVBGOD7HCIB7S8eLkLI,198800,In The Zone,Throwbacks
2,2,2,Beyoncé,spotify:track:0WqIKmW4BTrj3eJFmnCKMv,spotify:artist:6vWDO969PvNqNYHIOW5v0m,Crazy In Love,spotify:album:25hVFAxTlDvXbx2X2QkUkE,235933,Dangerously In Love (Alben für die Ewigkeit),Throwbacks
3,3,3,Justin Timberlake,spotify:track:1AWQoqb9bSvzTjaLralEkT,spotify:artist:31TPClRtHm23RisEBtV3X7,Rock Your Body,spotify:album:6QPkyl04rXwTGlGlcYaRoW,267266,Justified,Throwbacks
4,4,4,Shaggy,spotify:track:1lzr43nnXAijIGYnCT8M8H,spotify:artist:5EvFsr3kj42KNv97ZEnqij,It Wasn't Me,spotify:album:6NmFmPX56pcLBOFMhIiKvF,227600,Hot Shot,Throwbacks
...,...,...,...,...,...,...,...,...,...,...
67498,67498,39,James Arthur,spotify:track:5uCax9HTNlzGybIStD3vDh,spotify:artist:4IWBUUAFIplrNtaOHcJPRM,Say You Won't Let Go,spotify:album:7oiJYvEJHsmYtrgviAVIBD,211466,Back from the Edge,thinking of you
67499,67499,40,Big Words,spotify:track:0P1oO2gREMYUCoOkzYAyFu,spotify:artist:0sHN89qak07mnug3LVVjzP,The Answer,spotify:album:5jrsRHRAmetu5e7RRBoxj7,263679,"Hollywood, a Beautiful Coincidence",thinking of you
67500,67500,41,Allan Rayman,spotify:track:2oM4BuruDnEvk59IvIXCwn,spotify:artist:6Yv6OBXD6ZQakEljaGaDAk,25.22,spotify:album:3CbNgBzI7r9o0F6VjH9sTY,189213,Roadhouse 01,thinking of you
67501,67501,42,Jon Jason,spotify:track:4Ri5TTUgjM96tbQZd5Ua7V,spotify:artist:77bNdkKYBBmc30CisCA6tE,Good Feeling,spotify:album:2dZ7oVNQBeLlpoUYfbEsJP,194720,Good Feeling,thinking of you
67502,67502,43,Grizfolk,spotify:track:5RVuBrXVLptAEbGJdSDzL5,spotify:artist:6Xa4nbrSTfbioA4lLShbjh,Cosmic Angel - Acoustic From Capitol Studios,spotify:album:7D6Y19tjm4DQNch39FeWpO,257194,Cosmic Angel,thinking of you

We'll add in the audio features as columns, as well as the artist's popularity, the genres of the song, and the track's popularity.

In [11]:
import re
def features(trackuri):
    featuredict = sp.audio_features(trackuri)[0]
    artistid = sp.track(trackuri)['artists'][0]['id']
    artistpop = sp.artist(artistid)['popularity'] # add in artist popularity
    featuredict['artistpop'] = artistpop
    trackpop = sp.track(trackuri)['popularity'] # add in track popularity
    featuredict['trackpop'] = trackpop
    genres = sp.artist(artistid)['genres']
#     genres_und = []
#     for genre in genres:
#         if ' ' in genre:
#             genres_und.append(genre.replace(' ', '_'))
#         else: genres_und.append(genre)
    if genres:
        featuredict['genres'] = ' '.join(re.sub(' ','_',genre) for genre in genres) # short version
    else: 
        featuredict['genres'] = 'unknown'

    return featuredict

# print(type(sp.artist('2wIVse2owClT7go1WT98tk')['popularity']))
# print(sp.artist('2wIVse2owClT7go1WT98tk')['genres'])
# print(sp.track('0UaMYEvWZi0ZqiDOoHU3YI')['artists'][0]['id'])
print(features('spotify:track:0UaMYEvWZi0ZqiDOoHU3YI'))

In [22]:
featurelist = [] # list of dictionaries

for i, track in enumerate(df2['track_uri']):
    if i%100==0: print(i, end=' ')
    try: featurelist.append(features(track))
    except: continue
featuredf = pd.DataFrame(featurelist)
featuredf.rename({"uri":"track_uri"}, axis='columns', inplace=True)
featuredf

0 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400

In [14]:
# df2small = df2.head(100)
# final_100 = pd.merge(df2small, featuredf, how='outer')
# final_100
featuredf.head(2)

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,...,type,id,track_uri,track_href,analysis_url,duration_ms,time_signature,artistpop,trackpop,genres
0,0.904,0.813,4,-7.105,0,0.121,0.0311,0.00697,0.0471,0.810,...,audio_features,0UaMYEvWZi0ZqiDOoHU3YI,spotify:track:0UaMYEvWZi0ZqiDOoHU3YI,https://api.spotify.com/v1/tracks/0UaMYEvWZi0Z...,https://api.spotify.com/v1/audio-analysis/0UaM...,226864,4,69,66,dance_pop hip_hop hip_pop pop_rap r&b rap urba...
1,0.774,0.838,5,-3.914,0,0.114,0.0249,0.02500,0.2420,0.924,...,audio_features,6I9VzXrHxO9rA9A5euc8Ak,spotify:track:6I9VzXrHxO9rA9A5euc8Ak,https://api.spotify.com/v1/tracks/6I9VzXrHxO9r...,https://api.spotify.com/v1/audio-analysis/6I9V...,198800,4,81,81,dance_pop pop post-teen_pop

In [15]:
df2.head(2)

,Unnamed: 0,pos,artist_name,track_uri,artist_uri,track_name,album_uri,duration_ms,album_name,name
0,0,0,Missy Elliott,spotify:track:0UaMYEvWZi0ZqiDOoHU3YI,spotify:artist:2wIVse2owClT7go1WT98tk,Lose Control (feat. Ciara & Fat Man Scoop),spotify:album:6vV5UrXcfyQD1wu4Qo2I9K,226863,The Cookbook,Throwbacks
1,1,1,Britney Spears,spotify:track:6I9VzXrHxO9rA9A5euc8Ak,spotify:artist:26dSoYclwsYLMAKD3tpOr4,Toxic,spotify:album:0z7pVBGOD7HCIB7S8eLkLI,198800,In The Zone,Throwbacks

In [26]:
master = pd.merge(df2, featuredf, on='track_uri')
master.drop(columns=['Unnamed: 0','pos'], inplace=True)
# cols = master.columns.tolist()
# cols = [cols[7]] + cols[0:7] + cols[8:]
# master = master[cols]

In [30]:
# master.to_csv('out2.csv')
print(master.shape)
print(df2.shape)
print(featuredf.shape)

(102, 28)
(100, 10)
(100, 21)